### ISSUE TITLE
Manual pull button

### ISSUE THREAD

**Issue by cristianuibar** [presslabs/gitium#166]
In some instances, this makes sense and prevents you from manually going to the git webhook url where you simply see a blank page.

**Comment by sacp** [comment]
On my case, I always get a blank page. 

Checked the http status, and it's returning a "500 internal server error". 
If I test as a trigger from gitLab, it returns as well a 500 error: 
"Hook executed successfully but returned HTTP 500 "

I now have commits on both sides (wordpress and git) and can't force it to sync.

**Comment by pdobrescu** [comment]
Hi @sacp and thanks for your input here. A 500 error means something is wrong at the server side, which is preventing the pull or push operations to take place. Can you please check your server error log and see if you can find some useful information there? Depending on the server configuration, you might find an `error_log` file directly in the plugin folder - `/wp-content/plugins/gitium/`.

Please note that not all hosts allow the proper execution of Git commands and in certain cases, the error might come from limitations of memory, execution time or even CPU. 

The issue here refers only to a pull operation, as opposed to the `Merge changes` button, which does a merge between the changes from the site and the ones on the Git repository.

**Comment by DenisFlorin** [comment]
On the status page from Gitium, if only remote changes have been made, a pull button is now shown.
