### ISSUE TITLE
Is gitium still considered suitable for production?

### ISSUE THREAD

**Issue by XuluWarrior** [presslabs/gitium#190]
There hasn't been a code update for three years.  Which either says the code is rock solid or it's out of date.

**Comment by bogdanpetrea** [comment]
Hi @XuluWarrior! We are still using it in production, and for our use case it does the job... so probably the former more than the latter.

**Comment by ibes** [comment]
Just getting started with Gitium. 
This seems to be an amazing tool for the WordPress eco system. 
I don't understand, that it's not widely known and use. 

Seems to need some work to be compatible with PHP8+

And it seems like it is not getting love from Presslabs anymore?!

Any ideas why?

**Comment by cristianuibar** [comment]
Hello @ibes ,

We're still maintaining the plugin as it's being actively used by all of our customers right now, all running on PHP8 as this is the minimum on our platform.

I'd say it's in a low-maintenance mode right now, and you are correct, no new features have been added lately, but if any critical bug is found, we'll for sure address it.

Please let me know if you see any function that is not php8 ready, and I'll fix it.

**Comment by ibes** [comment]
@cristianuibar 

That is delightful to hear!
It's an awesome tool and I am stunned that it's not widely known and used "everywhere" :)

I needed to change something like here:
https://github.com/presslabs/gitium/pull/158 (using the commentend out `$wordpress_loader` worked for me. Not tried the fix in this pull request)

And I had to change this line
`$response = array_map( create_function( '$b', 'return str_replace("origin/","",$b);' ), $response );` in git-wrapper.php

But I just see: The WordPress.org version is not up to date. 
Here on Github this is already fixed. 

Would you be so kind and refresh the Version on wordpress.org if possible?

Likely my pain points are not your paint points just because the version on Github is up to date but the WordPress.org version is one or two steps behind. 

I want to make sure to express:
I thing this plugin is an awesome service to the WordPress community and I am delighted that it in deed is maintained.

**Comment by DenisFlorin** [comment]
The fix is already in place for the create_function on wp.org. 

I will close this for now and continue investigating the problem #158
