### ISSUE TITLE
Use existing git repo and branching

### ISSUE THREAD

**Issue by kosir** [PressLabs/gitium#98]
Hi, perfect plugin, thanks so much!!!!
I have two questions / feature requests...
First, I use wordpress on openshift, where is existing git deployment already installed, so I can have problems if I do remote push/pull from wordpress deployment directory (where is gitium), to openshift repo dir (where is openshift git with deployment scripts etc). Git doesn't like nested repositories, as you know... So my question is, how to use gitium on existing openshift repo, so I can have all wp changes recorded there (and other gitium goodies).
Second question is about branching, I don't know if it is currently available from wp interface. If yes, forget about this, if not, please consider this as feature request.
Thanks in advance for any reply.

**Comment by Marius786** [comment]
Thanks a for your feedback :)

1. Can you please give us a public example of one repo with openshift in order to see the openshift git structure? If you want to change the root dir of gitium you can use the 'GIT_DIR' constant, just define it in wp-config.php file, see https://github.com/PressLabs/gitium/blob/master/gitium/inc/class-git-wrapper.php#L613 I think your problem is 'multiple parent projects' If this is the problem then the issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other. see https://git-scm.com/book/en/v2/Git-Tools-Submodules So if this is the problem then one of your project (openshift or gitium) must be able to handle the submodules. The gitium doesn't handle (for the moment) submodules so only openshift must be compatible with submodules. If the openshift support submodules, then you just have to take care that the root dir for openshift is above the root dir of gitium by defining the GIT_DIR.

2. The branch can be chosen once on the installing steps, after that you must disconnect and connect again if you want to change the branch.

**Comment by kosir** [comment]
That's all I wanted to know, so both is already solved, thank you for detailed answer!
Thanks again for this great plugin!
